version: '3'
services:
  api:
    container_name: nu-api
    restart: always
    build: ./backend/api
    ports:
      - '8888:8888'
    links:
      - db
    volumes:
      - ./backend/api:/usr/src/app/
  scrobble-service:
    container_name: nu-scrobbler
    restart: always
    build: ./backend/services/SpotifyScrobbler
    links:
      - db
    volumes:
      - ./backend/services/SpotifyScrobbler:/usr/src/app/
  frontend:
    container_name: nu-frontend
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app/
  db:
    image: mongo:4.0.10
    ports:
      - '27017:27017'
