version: '3'
services:
  backend:
    container_name: nu-backend
    restart: always
    build: ./backend
    ports:
      - '8888:8888'
    links:
      - db
    volumes:
      - ./backend:/usr/src/app/
  frontend:
    container_name: nu-frontend
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app/
  db:
    image: mongo:4.0.10
    ports:
      - '27017:27017'
